# EDA Server Configuration
# All thresholds and parameters centralized for easy tuning

# Missing Data Analysis
missing_data:
  column_drop_threshold: 0.50  # 50% - drop columns with >50% missing data
  row_drop_threshold: 0.50     # 50% - drop rows with >50% missing values
  systematic_correlation_threshold: 0.70  # High correlation for systematic missingness
  imputation:
    skew_threshold: 1.0        # Use median if |skew| > 1, else mean
    categorical_mode_threshold: 0.20  # Only impute if missing < 20%

# Outlier Detection
outlier_detection:
  iqr_factor: 1.5              # Standard IQR multiplier
  contamination_default: 0.05  # 5% expected outliers for model-based methods
  mahalanobis_confidence: 0.975  # Chi-square confidence level
  max_columns_visualized: 10   # Limit columns for performance
  sample_size_limit: 10000     # Sample size for large datasets

# Schema Inference
schema_inference:
  id_uniqueness_threshold: 0.90  # 90% uniqueness for ID detection
  datetime_success_rate: 0.80   # 80% success rate for datetime inference
  precision_sample_size: 100    # Sample size for precision/scale inference
  max_sample_values: 5          # Max sample values to show

# Feature Transformation
feature_transformation:
  rare_category_threshold: 0.005  # 0.5% threshold for rare categories
  vif_severe_threshold: 10.0      # VIF > 10 indicates severe multicollinearity
  vif_moderate_threshold: 5.0     # VIF > 5 indicates moderate multicollinearity
  boxcox_epsilon: 1e-6            # Small epsilon for Box-Cox shifting
  skew_improvement_threshold: 0.5 # Minimum skewness improvement for transformation
  binning_n_bins: 5               # Default number of bins for quantile binning
  supervised_binning_min_samples: 10  # Minimum samples per bin

# Visualization
visualization:
  correlation_sample_size: 10000  # Sample size for correlation matrices
  max_points_scatter: 5000        # Max points for scatter plots
  figure_dpi: 150                 # DPI for saved figures
  correlation_label_threshold: 0.5 # Show labels for correlations > 0.5

# Performance
performance:
  memory_warning_threshold: 1000  # MB - warn if dataset > 1GB
  max_rows_processed: 100000      # Max rows for intensive operations
  chunk_size: 10000               # Chunk size for large dataset processing

# Human Checkpoints
checkpoints:
  require_approval: true          # Whether to require human approval
  approval_timeout: 300           # Seconds to wait for approval
  auto_approve_small_changes: true  # Auto-approve minor transformations 